!> @file uparam.f
!! @ingroup uparam
!! @brief Set of subroutines to read/write user runtime parameters.
!! @author Adam Peplinski
!! @date Mar 7, 2016
!=======================================================================
!! @brief Read user runtime parameters defined in USERPAR include file.
!! @ingroup uparam
!! @param[in]  iunit    file unit
!! @note This interface is defined in @ref runprm_in
!! @warning This routine has to be modified by the user or generated by
!!  script, as it shoud include user specified parameters. If there are
!!  no user defined parameters use [dummy] (@ref upardummy) submodule.
!!  Use this routine as and example only.
!! @todo Develop script generating this routine or move to user space
!! @todo Check iostat value for missing namelist in the file
!! @see @ref readers_writers_page
      subroutine user_param_in(iunit)
      implicit none

      include 'SIZE_DEF'
      include 'SIZE'            !
      include 'PARALLEL_DEF' 
      include 'PARALLEL'        ! ISIZE, WDSIZE, LSIZE,CSIZE
      include 'USERPAR'         !

!     argument list
      integer iunit

!     local variables
      integer ierr

!     namelists; cannot be empty
      namelist /USERPAR/ UPRM_PRB
!-----------------------------------------------------------------------
!     default values
      UPRM_PRB = 10
!     read the file
      ierr=0
      if (NID.eq.0) then
        rewind(iunit)
        read(unit=iunit,nml=USERPAR,iostat=ierr)
!     add exceptions in the future and check
!     if it is parameter and compiler independent
!     iostat
!     84 - NAMELIST group header not found in external file
!     85 - NAMELIST group header not found in internal file

      endif
      call err_chk(ierr,'Error reading USERPAR parameters.$')

!     broadcast data
      call bcast(UPRM_PRB,ISIZE)

      return
      end
!=======================================================================
!! @brief Write user runtime parameters defined in USERPAR include file
!! @ingroup uparam
!! @param[in]  iunit    file unit
!! @note This interface is defined in @ref runprm_out
!! @warning This routine has to be modified by the user or generated by
!!  script, as it shoud include user specified parameters. If there are
!!  no user defined parameters use [dummy] (@ref upardummy) submodule.
!!  Use this routine as and example only.
!! @todo Develop script generating this routine or move to user space
!! @see @ref readers_writers_page
      subroutine user_param_out(iunit)
      implicit none

      include 'SIZE_DEF'
      include 'SIZE'            ! NID
      include 'USERPAR'         !

!     argument list
      integer iunit

!     local variables
      integer ierr

!     namelists; cannot be empty
      namelist /USERPAR/ UPRM_PRB
!-----------------------------------------------------------------------
      ierr=0
      if (NID.eq.0) then
         write(unit=iunit,nml=USERPAR,iostat=ierr)
      endif
      call err_chk(ierr,'Error writing USERPAR parameters.$')

      return
      end
!=======================================================================
